### ISSUE TITLE
Link hover opacity set in base

### ISSUE THREAD

**Issue by dickieirwin** [victoriauniversity/vuw-styleguide#4]
https://github.com/victoriauniversity/vuw-styleguide/blob/develop/src/assets/toolkit/styles/_generic.typography.scss#L170

Yeah nah

**Comment by dickieirwin** [comment]
Lets test this for tracking issues

**Comment by voroniol** [comment]
@dickieirwin burn it with fire. From hipchat:

> `transparentize($color-links, .8)` should act the same

**Comment by voroniol** [comment]
Q: how'd you sync these with jira tracking?

**Comment by dickieirwin** [comment]
@voroniol no idea

**Comment by NeoGenet1c** [comment]
Fixed, closing...
