### ISSUE TITLE
Responsive break point differ from vic standard

### ISSUE THREAD

**Issue by dickieirwin** [victoriauniversity/vuw-styleguide#5]
https://github.com/victoriauniversity/vuw-styleguide/blob/develop/src/assets/toolkit/styles/_settings.responsive.scss#L13

![screen shot 2016-09-28 at 4 55 45 pm](https://cloud.githubusercontent.com/assets/5124035/18900310/b1353af2-859c-11e6-8731-7cb653bba40c.png)

**Comment by NeoGenet1c** [comment]
Yep, this brings 5 levels of responsiveness and thus adds more flexibility. 

You do not have to use all of them for every single responsive element so it shouldn't add unnecessary styles. You only use what you need.

Do you see any other issues/dangers here?
